### ISSUE TITLE
sphinx special characters in file names.

### ISSUE THREAD

**Issue by adrienlaveau** [shimizukawa/freia.jp#8]
Good morning Shimizukaya San,

I am working on the development of a software called UniPlot (uniplot.com). All our documentation and website is based on Sphinx. Up to now we were still using python 2.7 and I am trying to make the jump to python3.

I encountered several issue as expected but the latest one I cannot solve is putting me in a lot of trouble. I have a lots of file name with special characters like "{" or "@".
During sphinx conversion, those characters gets converted to their ASCII code which provokes issues when running sphinx-build -b html. I get the error 
`HHC5013: Error:
runtime error R6002
- floating point not loaded` 

Probably because files are not found. But I do not get interesting log info when this happens. 

I have written the following question in stackoverflow : https://stackoverflow.com/questions/78328719/htmlhelp-file-produced-with-python3-11-sphinx-7-2-6-cannot-be-compiled-with-hhc

If you could have a look I would greatly appreciate.

Thanks for all the work on python.

Adrien

(note: the contact form from your website leads to create this issue, I hope it is the correct way to contact you)

**Comment by shimizukawa** [comment]
I'll close it since the topic is not related to this repository.
I see that it has already been answered.
